# Generated by Django 5.0.4 on 2024-04-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=40)),
                ('species', models.CharField(max_length=30)),
                ('age', models.IntegerField(verbose_name=100)),
                ('color', models.CharField(max_length=20)),
                ('food_preference', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
